sudo choco install adb -y
sudo choco install AdoptOpenJDK -y
sudo choco install AdoptOpenJDKjre  -y
sudo choco install advanced-installer  -y
sudo choco install aida64-business  -y
sudo choco install anydesk  -y
sudo choco install chocolateygui -y
sudo choco install curl -y
sudo choco install docker-desktop  -y
sudo choco install dotnet -y
sudo choco install etcher -y
sudo choco install Explorerplusplus -y
sudo choco install firefox -y
sudo choco install flutter -y
sudo choco install git -y
sudo choco install github-desktop  -y
sudo choco install golang -y
sudo choco install gotop -y
sudo choco install gsudo  -y
sudo choco install hwinfo  -y
sudo choco install jq  -y
sudo choco install marktext -y
sudo choco install microsoft-edge -y
sudo choco install mingw -y
sudo choco install netlimiter -y
sudo choco install nodejs-lts -y
sudo choco install office-tool  -y
sudo choco install openvpn  -y
sudo choco install potplayer  -y
sudo choco install powershell-core  -y
sudo choco install python -y
sudo choco install rufus  -y
sudo choco install spotify  -y
sudo choco install teamviewer  -y
sudo choco install telegram  -y
sudo choco install vmwareworkstation  -y
sudo choco install vscode  -y
sudo choco install vscode-insiders  -y
sudo choco install wget -y
sudo choco install winfetch  -y
sudo choco install winrar -y
sudo choco install wireguard  -y
sudo choco install yarn  -y
sudo choco install zalopc -y